openapi: 3.0.0
info:
  title: Tshirt store API
  description: API for tshirt online store
  version: 1.0.0
  contact:
    email: neelabhnagaich@gmail.com

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth: # arbitrary name for the security scheme; will be used in the "security" key later
      type: apiKey
      in: cookie
    BearerAuth:
      type: http
      scheme: bearer
paths:
  /dummy:
    get:
      tags:
        - String
      summary: reurns a greeting message from API
       
      responses:
        200:
          description: All good response
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: Bad request
        500: 
          description: Internal Server error